name: Deploy a Canary Build
on:
  workflow_dispatch:
    branches-ignore:
      - main
jobs:
  deploy_canary:
    name: Build And Deploy Canary Release
    runs-on: ubuntu-latest
    environment: canary
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"

      - name: Lerna Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          preId=$(git rev-parse --abbrev-ref HEAD)
          echo "Publishing a canary release..."
          npx lerna publish \
            --canary \
            --force-publish \
            --preid canary-$preId \
            --conventional-commits \
            --changelog-preset @aabenoja/conventional-changelog-eslint-lerna \
            --yes
