name: Preproduction Release
on:
  push:
    branches:
      - pre-prod
jobs:
  test:
    name: Test with Node v${{matrix.node}}
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/pre-prod' && !contains(github.event.head_commit.message, '[skip-release]') }}
    strategy:
      matrix:
        node: [lts/*, node]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}

      - name: Use Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run Tests
        working-directory: packages/es-components
        run: |
          npm test

  npm:
    if: ${{ github.ref == 'refs/heads/pre-prod' && !contains(github.event.head_commit.message, '[skip-release]') }}
    needs: test
    name: Publish Pre-Prod NPM Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          ref: pre-prod
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"

      - name: Lerna Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          npx lerna publish --conventional-commits --changelog-preset @aabenoja/conventional-changelog-eslint-lerna --conventional-prerelease --dist-tag pre-prod --preid pre-prod --allow-branch pre-prod --yes
  docs:
    if: ${{ github.ref == 'refs/heads/pre-prod' }}
    needs: npm
    name: Publish Docs to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          ref: pre-prod
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"

      - name: Rebuild Pre-Prod Docs
        working-directory: packages/es-components
        run: |
          npm run pre-prod-sg-build

      - name: Configure docs changes
        run: |
          git checkout gh-pages
          rm -rf build/
          mkdir -p pre-prod
          cp -r ./packages/es-components/docs/pre-prod/* ./pre-prod
          git add pre-prod
          DIFF_RESULT=$(git diff --staged --quiet --exit-code; echo "$?")
          HAS_CHANGES=$(
            if [ $DIFF_RESULT -eq 0 ]
            then echo "false"
            else echo "true"
            fi
          )
          echo "Has docs changes? $HAS_CHANGES"
          echo "HAS_CHANGES=$HAS_CHANGES" >> $GITHUB_ENV

      - name: Publish docs to github pages
        if: env.HAS_CHANGES == 'true'
        run: |
          git commit -m "Deploy es-component pre-prod docs to gh-pages"
          git push origin gh-pages
